import React, { useState, useEffect, useRef } from 'react';
import { FiX, FiSend, FiCpu, FiMessageSquare, FiTrash2, FiShare2, FiFileText } from 'react-icons/fi';
import { ChatMessage } from '@/services/IntelligenceAIService';
import { TankIQService } from '@/services/TankIQService';
import { useAuth } from '@/hooks/useAuth';
import tankIQRobot from '@/assets/tankiq-robot.png';
import './TankIQSidebar.css';

interface TankIQSidebarProps {
    isOpen: boolean;
    onClose: () => void;
}

export const TankIQSidebar: React.FC<TankIQSidebarProps> = ({ isOpen, onClose }) => {
    const { currentUser } = useAuth();
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [inputValue, setInputValue] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const scrollRef = useRef<HTMLDivElement>(null);
    const serviceRef = useRef<TankIQService | null>(null);

    useEffect(() => {
        if (currentUser?.stationId && !serviceRef.current) {
            serviceRef.current = new TankIQService(currentUser.stationId);
            setMessages(serviceRef.current.getHistory());
        }
    }, [currentUser]);

    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, isTyping]);

    const handleSendMessage = async (text: string = inputValue) => {
        if (!text.trim() || !serviceRef.current) return;

        setInputValue('');
        setIsTyping(true);

        try {
            await serviceRef.current.sendMessage(text, (updatedHistory) => {
                setMessages(updatedHistory);
            });
        } catch (error) {
            console.error('TankIQ Error:', error);
            // Handle error message in chat if needed
        } finally {
            setIsTyping(false);
        }
    };

    const handleClearHistory = () => {
        if (window.confirm('Clear conversation history?') && serviceRef.current) {
            serviceRef.current.clearHistory();
            setMessages([]);
        }
    };

    const handleExportWhatsApp = () => {
        const lastMsg = messages.filter(m => m.role === 'assistant').pop();
        if (!lastMsg) return;
        
        const summary = lastMsg.content.substring(0, 500) + '...';
        const url = `https://wa.me/?text=${encodeURIComponent(`*TankIQ Insight for ${currentUser?.companyName}*:\n\n${summary}\n\nGenerated by IoTank V2.0.0`)}`;
        window.open(url, '_blank');
    };

    const quickSuggestions = [
        "When was my last refuel?",
        "Show my AGO daily burn rate",
        "Market price outlook",
        "Any active alerts?",
    ];

    if (!currentUser) return null;

    return (
        <aside className={`tankiq-sidebar ${isOpen ? 'open' : ''}`}>
            <div className="tankiq-header">
                <h2>
                    <div className="header-chip overflow-hidden !p-0 w-7 h-7 !bg-transparent !border-none">
                        <img 
                            src={tankIQRobot} 
                            style={{ width: '28px', height: '28px', borderRadius: '50%' }} 
                            className="object-cover" 
                            alt="IQ" 
                        />
                    </div>
                    TankIQ Assistant
                </h2>
                <button 
                    className="text-white opacity-50 hover:opacity-100 transition-opacity" 
                    onClick={onClose} 
                    title="Close TankIQ Assistant"
                >
                    <FiX size={24} />
                </button>
            </div>

            <div className="tankiq-content custom-scrollbar" ref={scrollRef}>
                {messages.length === 0 && (
                    <div className="flex flex-col items-center justify-center h-full px-8 text-center animate-in fade-in zoom-in duration-500">
                        <div className="w-20 h-20 bg-slate-50 rounded-3xl flex items-center justify-center mb-8 shadow-sm border border-slate-100/50">
                            <FiMessageSquare size={32} className="text-slate-400" />
                        </div>
                        <h3 className="text-2xl font-extrabold text-[#0f172a] tracking-tight">Grounded Intelligence</h3>
                        <p className="text-[15px] leading-relaxed text-slate-500 mt-4 max-w-[280px]">
                            I have access to your station's readings, deliveries, and market data. How can I help you manage your fuel today?
                        </p>
                    </div>
                )}
                
                {messages.map((msg, i) => (
                    <div key={i} className={`message ${msg.role} ${msg.role === 'assistant' ? 'glass-effect shadow-sm' : ''}`}>
                        {msg.role === 'assistant' && (
                            <div className="flex items-center gap-1 mb-1 text-[10px] font-bold text-purple-600 uppercase">
                                <FiCpu size={10} /> TankIQ Intelligence
                            </div>
                        )}
                        <div className="message-text whitespace-pre-wrap">
                            {msg.content || (msg.tool_calls ? 'Analyzing data...' : '')}
                        </div>
                    </div>
                ))}

                {isTyping && (
                    <div className="typing-indicator assistant">
                        <div className="dot-pulse"></div>
                        <span>TankIQ is reasoning...</span>
                    </div>
                )}
            </div>

            <div className="tankiq-footer">
                {messages.length === 0 && (
                    <div className="quick-suggestions">
                        {quickSuggestions.map((s, i) => (
                            <div key={i} className="suggestion-chip" onClick={() => handleSendMessage(s)}>
                                {s}
                            </div>
                        ))}
                    </div>
                )}

                <div className="chat-input-container">
                    <input 
                        type="text" 
                        placeholder="Ask TankIQ anything..." 
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                    />
                    <button className="send-btn" onClick={() => handleSendMessage()} disabled={isTyping} title="Send Message">
                        <FiSend size={18} />
                    </button>
                </div>

                <div className="export-actions">
                    <button className="export-btn whatsapp" onClick={handleExportWhatsApp} title="Share via WhatsApp">
                        <FiShare2 size={14} /> WhatsApp
                    </button>
                    <button className="export-btn pdf" onClick={() => window.print()} title="Export as PDF">
                        <FiFileText size={14} /> Save PDF
                    </button>
                    <button className="export-btn" onClick={handleClearHistory} title="Clear Chat">
                        <FiTrash2 size={14} />
                    </button>
                </div>
            </div>
        </aside>
    );
};
