/* eslint-disable @typescript-eslint/no-explicit-any */
import { TankReading, ShiftDocument } from '@/types';
import { format } from 'date-fns';

/**
 * Converts telemetry data to CSV format and triggers a download
 */
export const exportToCSV = (readings: TankReading[], filename: string) => {
    if (!readings.length) return;

    const headers = ['Timestamp', 'Fuel Level (%)', 'Volume (L)', 'Corrected Volume (L)', 'Temperature (°C)', 'Probe Status'];
    const rows = readings.map(r => [
        format(r.timestamp, 'yyyy-MM-dd HH:mm:ss'),
        r.fuelLevel.toFixed(2),
        r.volume.toFixed(0),
        r.volumeCorrected.toFixed(0),
        r.temperature.toFixed(1),
        r.metadata?.probeStatus || 'OK'
    ]);

    const csvContent = [
        headers.join(','),
        ...rows.map(row => row.join(','))
    ].join('\n');

    downloadFile(csvContent, `${filename}.csv`, 'text/csv');
};

/**
 * Converts telemetry data to JSON format and triggers a download
 */
export const exportToJSON = (data: any, filename: string) => {
    const jsonContent = JSON.stringify(data, null, 2);
    downloadFile(jsonContent, `${filename}.json`, 'application/json');
};

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Extend jsPDF interface to include autoTable
interface jsPDFWithAutoTable extends jsPDF {
    lastAutoTable: { finalY: number };
}

/**
 * Generates a formatted PDF report for operational compliance
 * Uses jspdf and jspdf-autotable for professional layout.
 */
export const generatePDF = (reportData: any, title: string) => {
    const doc = new jsPDF() as jsPDFWithAutoTable;
    const orgId = reportData.orgId || 'ioTank-industrial';
    const generatedDate = new Date().toLocaleString();

    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text(title, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Organization: ${orgId}`, 14, 28);
    doc.text(`Generated: ${generatedDate}`, 14, 33);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 38, 196, 38);

    // -- Summary Section --
    if (reportData.summary) {
        doc.setFontSize(14);
        doc.setTextColor(60, 60, 60);
        doc.text('Operational Summary', 14, 48);

        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        const splitSummary = doc.splitTextToSize(reportData.summary, 180);
        doc.text(splitSummary, 14, 55);
    }

    // -- Telemetry Table --
    if (reportData.readings && reportData.readings.length > 0) {
        const startY = reportData.summary ? 70 : 45;

        doc.setFontSize(14);
        doc.setTextColor(60, 60, 60);
        doc.text('Telemetry & Event Log', 14, startY - 5);

        const tableBody = reportData.readings.map((r: any) => [
            format(new Date(r.timestamp), 'yyyy-MM-dd HH:mm:ss'),
            `${r.fuelLevel.toFixed(2)}%`,
            `${r.volume.toFixed(0)} L`,
            `${r.temperature.toFixed(1)}°C`,
            r.metadata?.probeStatus || 'OK'
        ]);

        autoTable(doc, {
            startY: startY,
            head: [['Time', 'Level', 'Volume', 'Temp', 'Status']],
            body: tableBody,
            headStyles: { fillColor: [41, 128, 185], textColor: 255 },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            styles: { fontSize: 9 }
        });
    }

    // -- Footer --
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by IoTank Fuel Intelligence Hub - Industrial Compliance Module', 14, 285);
        doc.text(`Page ${i} of ${pageCount}`, 185, 285);
    }

    doc.save(`${title.replace(/ /g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

/**
 * Triggers a file download in the browser
 */
const downloadFile = (content: string, filename: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

/**
 * Generates a professional PDF report for a single shift
 */
export const generateShiftPDF = (
    shift: ShiftDocument,
    tankName: string,
    operatorName: string,
    companyName: string = 'IoTank Fuel Hub'
) => {
    const doc = new jsPDF() as jsPDFWithAutoTable;
    const shiftDate = format(new Date(shift.closedAt), 'MMMM dd, yyyy');
    const shiftTime = `${format(new Date(shift.openedAt), 'HH:mm')} - ${format(new Date(shift.closedAt), 'HH:mm')}`;
    const duration = (shift.durationMin / 60).toFixed(1);

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(companyName, 14, 20);

    doc.setFontSize(16);
    doc.setTextColor(60, 60, 60);
    doc.text('Shift Closure Report', 14, 30);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Tank: ${tankName}`, 14, 38);
    doc.text(`Date: ${shiftDate}`, 14, 43);
    doc.text(`Time: ${shiftTime}`, 14, 48);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 53, 196, 53);

    // Shift Summary Section
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text('Shift Summary', 14, 63);

    const summaryData = [
        ['Operator', operatorName],
        ['Duration', `${duration} hours`],
        ['Status', shift.reviewState === 'OPEN' ? 'Open' : 'Closed']
    ];

    autoTable(doc, {
        startY: 68,
        body: summaryData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 40 },
            1: { cellWidth: 'auto' }
        }
    });

    // Pump Readings Section
    const pumpStartY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text('Pump Readings', 14, pumpStartY);

    const pumpTableBody = Object.entries(shift.pumpReadings).map(([pumpId, p]) => {
        const volume = p.end - p.start;
        return [
            pumpId,
            p.start.toLocaleString(),
            p.end.toLocaleString(),
            `${volume.toFixed(1)} L`
        ];
    });

    const totalVolume = shift.volumeSoldLiters;

    pumpTableBody.push([
        { content: 'TOTAL', styles: { fontStyle: 'bold' } },
        '',
        '',
        { content: `${totalVolume.toFixed(1)} L`, styles: { fontStyle: 'bold' } }
    ] as any);

    autoTable(doc, {
        startY: pumpStartY + 5,
        head: [['Pump/Nozzle', 'Start Reading', 'End Reading', 'Volume Dispensed']],
        body: pumpTableBody,
        headStyles: { fillColor: [79, 70, 229], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 245, 250] },
        styles: { fontSize: 9 }
    });

    // Cash Reconciliation Section
    const cashStartY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text('Cash Reconciliation', 14, cashStartY);

    const varianceAmt = shift.variance.amount || 0;
    const varianceStatus = Math.abs(varianceAmt) < 1 ? 'Balanced' : (varianceAmt > 0 ? 'Overage' : 'Shortage');
    const varianceColor = Math.abs(varianceAmt) < 1 ? [34, 197, 94] : (varianceAmt > 0 ? [59, 130, 246] : [239, 68, 68]);

    const cashData = [
        ['Expected', `$${shift.expected.total.toFixed(2)}`],
        ['Collected (All methods)', `$${shift.received.total.toFixed(2)}`],
        [
            { content: 'Variance', styles: { fontStyle: 'bold' } },
            {
                content: `${varianceAmt > 0 ? '+' : ''}$${varianceAmt.toFixed(2)} (${varianceStatus})`,
                styles: { fontStyle: 'bold', textColor: varianceColor }
            }
        ]
    ];

    autoTable(doc, {
        startY: cashStartY + 5,
        body: cashData as any,
        theme: 'striped',
        styles: { fontSize: 10, cellPadding: 4 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 50 },
            1: { cellWidth: 'auto', halign: 'right' }
        }
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated: ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}`, 14, 285);
        doc.text(`Page ${i} of ${pageCount}`, 185, 285);
    }

    const filename = `Shift_Report_${tankName.replace(/ /g, '_')}_${format(new Date(shift.closedAt), 'yyyyMMdd_HHmm')}.pdf`;
    doc.save(filename);
};

/**
 * Exports multiple shifts to Excel format with summary and details sheets
 */
export const exportShiftsToExcel = (
    shifts: ShiftDocument[],
    tankNames: Record<string, string>
) => {
    // Create CSV content for Excel compatibility
    const headers = [
        'Shift Date',
        'Shift Time',
        'Tank',
        'Duration (hrs)',
        'Total Volume (L)',
        'Expected Cash',
        'Actual Cash',
        'Variance',
        'Status'
    ];

    const rows = shifts.map(shift => {
        const tankName = tankNames[shift.tankId] || shift.tankId;
        const shiftDate = format(new Date(shift.closedAt), 'yyyy-MM-dd');
        const shiftTime = `${format(new Date(shift.openedAt), 'HH:mm')}-${format(new Date(shift.closedAt), 'HH:mm')}`;
        const duration = (shift.durationMin / 60).toFixed(1);
        const totalVolume = shift.volumeSoldLiters;
        const varianceAmt = shift.variance.amount || 0;
        const status = Math.abs(varianceAmt) < 1 ? 'Balanced' : (varianceAmt > 0 ? 'Overage' : 'Shortage');

        return [
            shiftDate,
            shiftTime,
            tankName,
            duration,
            totalVolume.toFixed(1),
            shift.expected.total.toFixed(2),
            shift.received.total.toFixed(2),
            varianceAmt.toFixed(2),
            status
        ];
    });

    const csvContent = [
        headers.join(','),
        ...rows.map(row => row.join(','))
    ].join('\n');

    const filename = `Shift_History_${format(new Date(), 'yyyyMMdd_HHmmss')}`;
    downloadFile(csvContent, `${filename}.csv`, 'text/csv');
};
